[dependencies.compiler_builtins]
path = "../node_modules/@solana/web3.js/bpf-sdk/dependencies/rust-bpf-sysroot/src/compiler-builtins"
features = ["c", "mem"]

[target.bpfel-unknown-unknown.dependencies]
alloc = { path = "../node_modules/@solana/web3.js/bpf-sdk/dependencies/rust-bpf-sysroot/src/liballoc" }